# This file is generated by script/brew-cask.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
cask "gocode-desktop" do
  version "0.1.47"
  sha256 "cd427262d8240b5f0c046e6943b2142253e2e9b048b3796fed46064c0db9d12c"

  url "https://github.com/langazov/gocode/releases/download/v#{version}/gocode-desktop-#{version}-macos-universal.zip"
  name "gocode"
  desc "Desktop client for the gocode AI coding agent"
  homepage "https://github.com/langazov/gocode"

  livecheck do
    skip "Updated by the gocode release workflow."
  end

  # The app runs "gocode serve" for the folder you open, so it needs the CLI.
  depends_on formula: "langazov/tap/gocode"
  depends_on macos: :monterey

  app "Gocode Desktop.app"

  # The app is not signed or notarized, and casks quarantine what they
  # download, so Gatekeeper would refuse to open it. Clearing the flag is what
  # the release notes otherwise ask users to do by hand. Remove this once the
  # release is signed with a Developer ID.
  #
  # A declarative step, as Homebrew 7 requires: {{appdir}} is expanded by
  # Homebrew at install time, and the step sandbox may write to the app dir.
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Gocode Desktop.app"]
  end

  zap trash: [
    "~/Library/Application Support/dev.gocode.gocodeGui",
    "~/Library/Caches/dev.gocode.gocodeGui",
    "~/Library/Preferences/dev.gocode.gocodeGui.plist",
    "~/Library/Saved Application State/dev.gocode.gocodeGui.savedState",
  ]
end
