# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-mcp-server" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9a0ffbf86932609f3c5107c4033ba2c02f7466f297de7f56601e82b998b07c55"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0227692c83ddbaed5204e85a98746681f6c179935e14a5b80ca8993016891218"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4007f97682b817b38fc4d0c899c534b2f08c49cc26210d29a553a7de10eb6ec"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45c3fa1349ad295b4cc219720db6f4ded79ec288796311b19879c322ba8488fa"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "k8s-mcp-server"
  desc "Model Context Protocol server that exposes a Kubernetes cluster to AI agents: manage resources, troubleshoot problems, and debug applications."
  homepage "https://github.com/langazov/go-kubernetes-mcp-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-mcp-server"

  # No zap stanza required

end
