# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-mcp-server" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4af416b20c9dbf3a415aae2a8344683ca04c3f069ab7b2ea39651fe08de7eae2"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0e4531fb52213d4ab54d146928d7a92579ba37eb7db23dc3ed751e1dbdc0786"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b30146c76b54fe057f26721ad2832c4c2efb841ee78fd1f40b507fcefd9b34da"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a564c950346d74beb0d842fac8d95e07ca5d9e91ba7fa8ff40bc8fb16c39bcf9"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "k8s-mcp-server"
  desc "Model Context Protocol server that exposes a Kubernetes cluster to AI agents: manage resources, troubleshoot problems, and debug applications."
  homepage "https://github.com/langazov/go-kubernetes-mcp-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-mcp-server"

  # No zap stanza required

end
