# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-mcp-server" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "a20cbe89433738ad32188c97b34aebd54b93122ca5d2c5086111c0d8e60fd25b"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab67cfd1d4224cc0f59e93b60546b4780c0b2e91f90c7064b0ab9f8f0ae1052d"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a23978d9ba0e6d48c595e9cbb1507ea84d7762e6d2eac5356a2a914c739b9396"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a92c132db1b2735ea9d381dcc74d36f00e2b2ad7c763e7eb84bf28b713d63f4"
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v#{version}/k8s-mcp-server_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "k8s-mcp-server"
  desc "Model Context Protocol server that exposes a Kubernetes cluster to AI agents: manage resources, troubleshoot problems, and debug applications."
  homepage "https://github.com/langazov/go-kubernetes-mcp-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-mcp-server"

  # No zap stanza required

end
