# This file is generated by script/brew-formula.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
class Gocode < Formula
  desc "Terminal-based AI coding agent"
  homepage "https://github.com/langazov/gocode"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v0.1.11/gocode-0.1.11-macos-arm64.tar.gz"
      sha256 "37d2636ffd7d5881decf96bfcd0d37084ede2ea1c646f177d61c4d92b98b314a"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v0.1.11/gocode-0.1.11-macos-x64.tar.gz"
      sha256 "f56382ff995a6c1d33b5b9e5c5177610af857189fc565d24539884852c7bfb67"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v0.1.11/gocode-0.1.11-linux-arm64.tar.gz"
      sha256 "8c08d69b4d8ac758f17b015e3d382e06b1c2de6ee15a9b40efe827aa7de31a7d"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v0.1.11/gocode-0.1.11-linux-x64.tar.gz"
      sha256 "e747bf653e377dedcc8e9477235e0baa1f34ea2dd67acb560333bc05c9b146e8"
    end
  end

  def install
    bin.install "gocode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gocode --version")
  end
end
