# This file is generated by script/brew-formula.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
class Gocode < Formula
  desc "Terminal-based AI coding agent"
  homepage "https://github.com/langazov/gocode"
  license "MIT"

  on_macos do
    on_arm do
      url "https://s3.gocoder.org/releases/gocode/v0.1.43/gocode-0.1.43-macos-arm64.tar.gz"
      sha256 "027fcd69aa47e7f91e09ac6c0904f24fe7c9e126f388fea47a3db2aafa92f3c6"
    end
    on_intel do
      url "https://s3.gocoder.org/releases/gocode/v0.1.43/gocode-0.1.43-macos-x64.tar.gz"
      sha256 "1c5e633df1ede4f3fcef54ba00f21aa9a7f11f14373a0c347f072ef6beedb3d9"
    end
  end

  on_linux do
    on_arm do
      url "https://s3.gocoder.org/releases/gocode/v0.1.43/gocode-0.1.43-linux-arm64.tar.gz"
      sha256 "3be9d23a13d18494744c364cf5a53710cb94858072857a2e901f56086334d4c5"
    end
    on_intel do
      url "https://s3.gocoder.org/releases/gocode/v0.1.43/gocode-0.1.43-linux-x64.tar.gz"
      sha256 "2c2b7b7080efd52807a269dd9ab0e409bb6d5fdba8b6f60926c798f69cff6860"
    end
  end

  def install
    bin.install "gocode"
    # A general LSP server, not a gocode internal: editors are pointed at it
    # directly, and gocode's own registry finds it by name on PATH.
    bin.install "mdlsp"
    # The plugin stays out of PATH — it is not a command anyone runs — but
    # keeps its directory layout, since the loader resolves a plugin by
    # reading gocode-plugin.json next to the binary.
    libexec.install "rag-plugin"
  end

  # Wire both extras into the user's global config. Homebrew runs this as the
  # user, so it reaches ~/.config/gocode; the edits are idempotent, preserve
  # every other key, and refuse to rewrite a config carrying comments.
  #
  # The plugin is enabled by bare name. gocode searches <prefix>/libexec for
  # plugins, relative to its own binary (plugin.BundledRoots), so the name is
  # enough and the config stays free of installation-specific paths — it keeps
  # working across a Homebrew prefix change, and `gocode plugin disable
  # rag-plugin` is something a user can actually type.
  #
  # Earlier versions wrote the absolute libexec path instead, because no such
  # search path existed. The disable below removes that stale entry on
  # upgrade, and is a no-op on a fresh install. It matters: an absolute path
  # and a bare name are different refs that nothing deduplicates, so leaving
  # both would load rag-plugin twice and spawn two copies of it at every boot.
  #
  # A failure here is warned about, not raised: the binaries are installed and
  # usable either way, and a config this cannot parse is a reason to tell the
  # user rather than to fail their upgrade.
  def post_install
    [
      ["lsp", "enable", "mdlsp",
       "--global", "--command", opt_bin/"mdlsp", "--extensions", ".md,.markdown"],
      ["plugin", "disable", (opt_libexec/"rag-plugin").to_s, "--global"],
      ["plugin", "enable", "rag-plugin",
       "--global", "--options", '{"embeddingProvider":"openai"}'],
    ].each do |args|
      system bin/"gocode", *args
    rescue StandardError => e
      opoo "could not run 'gocode #{args[0]} #{args[1]}': #{e}"
      opoo "Wire it up by hand; 'brew info gocode' lists the commands."
    end
  end

  def caveats
    <<~EOS
      Two extras were installed alongside gocode and wired into
      ~/.config/gocode:

        mdlsp       markdown language server, started for .md files
        rag-plugin  semantic code search (rag_index / rag_search tools)

      rag-plugin embeds through an OpenAI-compatible endpoint, so it needs a
      credential before its tools will work:

        gocode auth login

      To turn either off again (the files stay installed):

        gocode lsp disable mdlsp
        gocode plugin disable rag-plugin
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gocode --version")
    assert_match "mdlsp", shell_output("#{bin}/mdlsp --version")
    # The manifest is what makes the directory loadable as a plugin.
    assert_predicate libexec/"rag-plugin/gocode-plugin.json", :exist?
  end
end
