# This file is generated by script/brew-formula.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
class Gocode < Formula
  desc "Terminal-based AI coding agent"
  homepage "https://github.com/langazov/gocode"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v0.1.12/gocode-0.1.12-macos-arm64.tar.gz"
      sha256 "92260addb1471326c6ed630f40d9ab24dbccb8caecde9286565fa4016cd6dc1b"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v0.1.12/gocode-0.1.12-macos-x64.tar.gz"
      sha256 "cad6e0d65c0fbdefcf07d6d45dfcbbc9fb62175eafc8cf4b66cef6b73fa2eb8b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v0.1.12/gocode-0.1.12-linux-arm64.tar.gz"
      sha256 "861a178362b3f5f544f8765ff0b4d50caf0d8416f55c6f4378cbc2b4984e5372"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v0.1.12/gocode-0.1.12-linux-x64.tar.gz"
      sha256 "e6cd416d82e453f5912f6d23e90d4a3fd7a88b853be83d83a49c08ed7fa7cbfe"
    end
  end

  def install
    bin.install "gocode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gocode --version")
  end
end
