# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sMcpServer < Formula
  desc "Model Context Protocol server that exposes a Kubernetes cluster to AI agents: manage resources, troubleshoot problems, and debug applications."
  homepage "https://github.com/langazov/go-kubernetes-mcp-server"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v0.1.1/k8s-mcp-server_0.1.1_Darwin_amd64.tar.gz"
      sha256 "dcfd928814c67f89dc13a38e709d48bf818174a886d7e5d4604edaa82bdca52e"

      define_method(:install) do
        bin.install "k8s-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v0.1.1/k8s-mcp-server_0.1.1_Darwin_arm64.tar.gz"
      sha256 "37fdfa14910da5caeb31ca15bc681930927120b1f56bd0d91fd6e885c6574ce0"

      define_method(:install) do
        bin.install "k8s-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v0.1.1/k8s-mcp-server_0.1.1_Linux_amd64.tar.gz"
      sha256 "878ac28303a82a32dedfb659427acee603bdade554c4c0c3b0af3e7df4e6478d"
      define_method(:install) do
        bin.install "k8s-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langazov/go-kubernetes-mcp-server/releases/download/v0.1.1/k8s-mcp-server_0.1.1_Linux_arm64.tar.gz"
      sha256 "99ddc30b1722582b741f1d8e8de59503c250faf7185578627ce1755744341c15"
      define_method(:install) do
        bin.install "k8s-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/k8s-mcp-server", "--help"
  end
end
